# -*- mode: org ; coding: utf-8-unix -*-
# last updated : 2016/10/07.16:25:13


#+TITLE:     Emacs Build Shells
#+AUTHOR:    yaruopooner
#+EMAIL:     [https://github.com/yaruopooner]
#+OPTIONS:   author:nil timestamp:t |:t \n:t ^:nil



* 動作環境
  ↓でテスト
  Windows 10/7 x86_64
  Cygwin x86_64 2.1.0(0.287/5/3) 2015-07-14 21:28

* 準備
#+begin_src shell-script
  git clone https://github.com/yaruopooner/emacs-build-shells.git
#+end_src
  またはzipをダウンロードして展開

* 手順１：MSYS2導入
  以下の手順を行うと自動でMSYS2をダウンロード・展開・起動される
  Cygwin か PowerShell どちらからでもインストール可能
  MSYS2はポータブル版を使用しているので環境を汚していないはず

** Cygwin からインストール
   #+begin_src shell-script
     cd emacs-build-shells
     ./install-msys2.sh
   #+end_src
   
** PowerShell からインストール
   実行にはPowerShell 5の環境が必要。(Windows10は最初から5だった気が)
   5未満の場合は以下からダウンロードしてインストール
   PowerShell 5.0(Windows Management Framework 5.0)
   https://www.microsoft.com/en-us/download/details.aspx?id=50395
   #+begin_src shell-script
     cd emacs-build-shells
     install-msys2.ps1
   #+end_src
   または
   エクスプローラーからinstall-msys2.ps1を実行する

** オプション
   install-msys2.XXX.options の記述を編集することにより
   ダウンロードするアーカイブ、起動する MinGW64/32 の設定が可能。
   install-msys2.XXX.options が存在しない場合デフォルト値が使用される

* 手順２：MSYS2パッケージアップデートとEmacsビルド
  以下の手順を行うと自動でMSYS2アップデートとEmacsアーカイブのダウンロード・展開・ビルドを行う。
  Emacsの実行に必要なDLLの依存解析を行い、必要なDLLがコピーされる。

  ※プロキシ経由を行っている場合は start.sh 実行前にシェル上で↓を行ってから実行、もしくは以下の設定を build-emacs.options に記述する
  #+begin_src shell-script
    $ export http_proxy="url:port"
    $ export https_proxy="url:port"
  #+end_src

  install-msys2 で起動された MinGW64/32 上で作業ディレクトリへ移動して start.sh を実行

  #+begin_src shell-script
    cd /tmp/build-shells
    ./start.sh
  #+end_src

  完了後にログが表示される。
  ※ログファイルとして残る。

  ビルドされたEmacsは↓に置かれるので emacs-XX.X ごと自分の環境へ移動して利用。
  /msys64/tmp/build-shells/build/XX/emacs-XX.X

** オプション
   build-emacs.options の記述を編集することにより
   ダウンロードするアーカイブ、パッチ、 configureの追加設定が可能。
   build-emacs.options が存在しない場合デフォルト値が使用される。

* 参考文献
  https://github.com/chuntaro/NTEmacs64
  http://cha.la.coocan.jp/doc/NTEmacsBuild251.html#sec-7-2

